
###
# Testes para acesso aos webservices HTTP providos pelo NodeJS
###

@hostname = localhost:9990

###

GET /contas HTTP/1.1
Host: {{hostname}}


###

GET /conta/1/lancamentos HTTP/1.1
Host: {{hostname}}

###

POST /conta/1/lancamentos HTTP/1.1
Host: {{hostname}}
Content-Type: application/json

{
    "_id": null,
    "conta_id": 1,
    "nr_referencia": "XX0101XX",
    "descricao": "Teste POST",
    "data": "{{$datetime "YYYY-MM-DD"}}",
    "valor": 45.33
}

###

POST /upload HTTP/1.1
Host: {{hostname}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="myFileUpload"; filename="Copy of Exemplo_Omni-Channel_V01.csv"
Content-Type: text/csv

< C:\Users\VMWorkJayme\Downloads/Copy of Exemplo_Omni-Channel_V01.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

POST /upload HTTP/1.1
Host: {{hostname}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="myFileUpload"; filename="Movimentos 2020-04-13 a 2020-06-30.xlsx"


< C:\Users\VMWorkJayme\Downloads/Movimentos 2020-04-13 a 2020-06-30.xlsx
------WebKitFormBoundary7MA4YWxkTrZu0gW--